apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc006
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
