apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-pvc008
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
