apiVersion: v1
kind: PersistentVolume
metadata:
  name: stpv01
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /public/04
    server: k8s-master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stpv02
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /public/05
    server: k8s-master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stpv03
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /public/06
    server: k8s-master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stpv04
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /public/07
    server: k8s-master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stpv05
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /public/08
    server: k8s-master
