---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd-3
spec:
  containers:
  - name: iscsipd-rw3
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: iscsipd-rw3
      readOnly: true
  volumes:
  - name: iscsipd-rw3
    iscsi:
      targetPortal: 192.168.122.85:3260
      iqn: iqn.2017-05.com.example:rhel7
      lun: 0
      fsType: ext4
