apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
        - name: data
          mountPath: /dev/loop2
  volumes:
    - name: data
      hostPath:
        path: /dev/loop2
        type: BlockDevice
