apiVersion: v1
kind: PersistentVolume
metadata:
  name: htpv01
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /dev/loop2
    type: BlockDevice
