apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: nginx-pvc01
