apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod3
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
      - containerPort: 80
      volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
        - name: data2
          mountPath: /mnt
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: nginx-pvc01
    - name: data2
      persistentVolumeClaim:
        claimName: nginx-pvc02
