apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: centos
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    command:
      - tail
      - -f
      - /dev/null
  volumes:
  - name: cache-volume
    emptyDir: {}
