apiVersion: v1
kind: Pod
metadata:
  name: centos7-test2
spec:
  containers:
    - name: centos7-container2
      image: centos7:test
      command:
        - tail
        - -f
        - /dev/null
      resources:
        requests:
          memory: "4000Mi"
          cpu: "3500m"
        limits:
          memory: "5120Mi"
          cpu: "4000m"
