apiVersion: v1
kind: Pod
metadata:
  name: centos7-test
spec:
  containers:
    - name: centos7-container
      image: centos7:test
      command:
        - tail
        - -f
        - /dev/null
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "2048Mi"
          cpu: "500m"
