apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-pv001
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  persistentVolumeReclaimPolicy: Recycle
  iscsi:
    targetPortal: 192.168.122.228:3260
    iqn: iqn.2017-05.com.example:fc25
    lun: 0
    fsType: ext4
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc001
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: block-nginx-pod1
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
      - containerPort: 80
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: block-pvc001
