apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeType: block
  persistentVolumeReclaimPolicy: Recycle
  iscsi:
    targetPortal: 192.168.122.228:3260
    iqn: iqn.2017-05.com.example:fc25-2
    lun: 0
    fsType: ext4
    readOnly: true
