apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  iscsi:
    targetPortal: 192.168.122.85:3260
    portals: ['192.168.122.7:3260']
    iqn: iqn.2017-05.com.example:rhel7
    lun: 0
    fsType: ext4
    readOnly: true
    chapAuthDiscovery: false
    chapAuthSession: true
    secretRef:
      name: chap-secret
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc001
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: nginx-pvc001
