apiVersion: v1
kind: Pod
metadata:
  name: centos
  labels: 
    app: centos
spec:
  containers:
    - name: centos-container
      image: centos:latest
      command:
        - tail
        - -f
        - /dev/null
