apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
      - containerPort: 80
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: block-pvc001
