apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-pv001
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 192.168.122.85:3260
    portals: ['192.168.122.7:3260']
    iqn: iqn.2017-05.com.example:rhel7
    lun: 0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc001
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  volumeName: block-pv001
---
