kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: "iscsi"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
