apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-pv001
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  fc:
    targetWWNs: ["50060e801049cfd1"]
    lun: 0
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-pvc001
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pause-pod
spec:
  containers:
    - name: pause1
      image: kubernetes/pause
      volumeMounts:
        - name: data
          mountPath: /mnt
    - name: pause2
      image: kubernetes/pause
      volumeMounts:
        - name: data
          mountPath: /mnt2
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: file-pvc001
        readOnly: true
