apiVersion: v1
kind: Service
metadata:
  name: dev-np
spec:
  selector:
    run: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  externalIPs: 
    - 35.184.129.143

