apiVersion: v1
kind: Service
metadata:
  name: dev-np
spec:
  selector:
    run: test
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31707
      name: http
