apiVersion: v1
kind: Pod
metadata:
  labels:
    test: iscsi-pvc-pod
  name: iscsi-pv-pod1
spec:
  containers:
  - name: iscsi-pv-busybox
    image: busybox
    command: ["sleep", "60000"]
    volumeDevices:
    - name: iscsi-vol1
      devicePath: /dev/xvda
  volumes:
  - name: iscsi-vol1
    persistentVolumeClaim:
      claimName: testclaim
