apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-pv001
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 192.168.122.85:3260
    portals: ['192.168.122.7:3260']
    iqn: iqn.2017-05.com.example:rhel7
    lun: 0
    fsType: ext4
