---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: iscsipd-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: iscsipd-rw
  volumes:
  - name: iscsipd-rw
    iscsi:
      targetPortal: 192.168.122.34:3260
      portals: ['192.168.122.34:3260', '192.168.122.244:3260']
      iqn: iqn.2017-05.com.example:k8sbuild
      lun: 0
      fsType: ext4
      readOnly: true
