apiVersion: v1
kind: PersistentVolume
metadata:
  name: htpv01
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/pv01
