apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc01
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
    - ReadWriteOnce
  volumeType: block
  resources:
    requests:
      storage: 1Gi
