---
apiVersion: v1
kind: Pod
metadata:
  name: iscsi-pd
spec:
  containers:
  - name: iscsipd-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: vol01
  volumes:
  - name: vol01
    iscsi:
      targetPortal: 192.168.122.231:3260
      portals: ['192.168.122.228:3260']
      iqn: iqn.2017-05.com.example:fc25
      lun: 0
      fsType: ext4
      readOnly: true
      initiatorName: iqn.1994-05.com.redhat:185ce16b55ad
