---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: iscsipd-ro
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: iscsivol
  volumes:
  - name: iscsivol
    iscsi:
      targetPortal: 192.168.122.85:3260
      iqn: iqn.2017-05.com.example:rhel7
      lun: 0
      fsType: ext4
      readOnly: true
      chapAuthDiscovery: false
      chapAuthSession: true
      secretRef: 
         name: chap-secret
