apiVersion: v1
kind: Pod
metadata:
  name: cent7-cap-drop
spec:
  containers:
    - name: cent7-cap-drop
      image: centos7:test
      command:
        - tail
        - -f
        - /dev/null
      securityContext:
        capabilities:
          drop:
            - LEASE
