apiVersion: v1
kind: Pod
metadata:
  name: cent7-cap-test
spec:
  containers:
    - name: cent7-cap-test
      image: centos7:test
      command:
        - tail
        - -f
        - /dev/null
      securityContext:
        capabilities:
          add:
            - SYS_ADMIN
            - LEASE
