---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd2
spec:
  containers:
  - name: iscsipd-rw2
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: iscsipd-rw2
  volumes:
  - name: iscsipd-rw2
    iscsi:
      targetPortal: 192.168.122.228:3260
      iqn: iqn.2017-05.com.example:fc25
      lun: 0
      fsType: ext4
      readOnly: true
